source ${HOME}/.zsh/local_before.zsh
source ${HOME}/.zsh/settings.zsh
source ${HOME}/.shell/environment.sh
source ${HOME}/.zsh/private.zsh
source ${HOME}/.shell/aliases.sh
source ${HOME}/.zsh/prompt.zsh
source ${HOME}/.shell/theme.sh
source ${HOME}/.shell/functions.sh
source ${HOME}/.shell/extras.sh
source ${HOME}/.zsh/local_after.zsh
